name: imageConverter

namespace: kavanet-io

deployment:
  - name: imageconverter
    image: 192.168.1.61:5000/imageconverter
    ports:
    - port: 80

service:
  clusterIP:
    - name: imageconverter
      selector: imageconverter
      ports:
      - port: 80

ingress:
  - name: imageconverter
    selector: imageconverter
    path: /
    port: 80
    host: imageconverter.kavanet.io
