name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: 2779267bb50ce21b04a95792d21a905ce522f471

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
