name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: f1c742b1a816970ff17ebfc8f3be74a3b62853e9

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
