name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: 1839ae0e41cab7ca2c366015b0efdb279ecc00a4

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io
    # env: # not sure if this is correct, val must be "true" to work so meh
    #   - name: LOCAL
    #     value: "false"

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
