name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: 1e7aa546fdbfe98e945fe9b173f5c96bb9a3f83d

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
