name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: 5d3e8ffbc0a05fa7db1620c1e0a91bc60b546471

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io
    # env: # not sure if this is correct, val must be "true" to work so meh
    #   - name: LOCAL
    #     value: "false"

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
