name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: 9fe89276aa09b404d503b5f38cb95cd3a0446cf0

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
