name: kavanet-io

namespace: kavanet-io
env:
  APP_VERSION: ba43585da438475feae5eeb538a6c7ef31bd2af3

deployment:
  - name: kavanet-io
    image: invisibug/kavanet-io

service:
  loadBalancer:
    - name: kavanet-io
      selector: kavanet-io
      port: 80
      containerPort: 3000

ingress:
  - name: kavanet.io
    selector: kavanet-io
    path: /
    port: 3000
    host: kavanet.io
